apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hosts.fadk8sctrl.fortinet.com
  annotations:
    "helm.sh/resource-policy": keep
spec:
  preserveUnknownFields: false
  group: fadk8sctrl.fortinet.com
  names:
    kind: Host
    plural: hosts
    singular: host
    shortNames:
      - host
  scope: Namespaced
  versions:
    -
      name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: HOSTNAME
          type: string
          jsonPath: .spec.hostname
        - name: DOMAIN
          type: string
          jsonPath: .spec.domain
        - name: STATUS
          type: string
          jsonPath: .status.status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - hostname
                - domain
                - vdom
              properties:
                hostname:
                  type: string
                  pattern: '^(?:@$|\*$|(?:\*\.)*(?:[a-zA-Z0-9-]{1,63}\.)*[a-zA-Z]{2,63}$)'
                domain:
                  type: string
                  pattern: '^[a-zA-Z0-9][a-zA-Z0-9.-]{0,61}[a-zA-Z0-9.]$'
                dnsPolicy:
                  type: array
                  items:
                    type: string
                    pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                  x-kubernetes-validations:
                    - rule: "size(self) <= 64"
                singleRecord:
                  type: string
                  enum: [ enable, disable ]
                  default: disable
                persistence:
                  type: string
                  enum: [ enable, disable ]
                  default: disable
                lbMethod:
                  type: string
                  enum: [ weight, topology, global-availability ]
                  default: weight
                feedbackIPv4:
                  type: string
                  pattern: '^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]?|0)\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]?|0)$'
                feedbackIPv6:
                  type: string
                  pattern: '^(([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){1,7}:)|(([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,5}(:[0-9A-Fa-f]{1,4}){1,2})|(([0-9A-Fa-f]{1,4}:){1,4}(:[0-9A-Fa-f]{1,4}){1,3})|(([0-9A-Fa-f]{1,4}:){1,3}(:[0-9A-Fa-f]{1,4}){1,4})|(([0-9A-Fa-f]{1,4}:){1,2}(:[0-9A-Fa-f]{1,4}){1,5})|([0-9A-Fa-f]{1,4}:((:[0-9A-Fa-f]{1,4}){1,6}))|(:((:[0-9A-Fa-f]{1,4}){1,7}|:))$'
                fortiview:
                  type: string
                  enum: [ enable, disable ]
                  default: disable
                virtualServerPools:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                      topology:
                        type: string
                        pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                      isp:
                        type: string
                        pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                      weight:
                        type: integer
                        minimum: 1
                        maximum: 255
                        default: 1
                      virtualServerPool:
                        type: object
                        properties:
                          preferred:
                            type: string
                            enum: [ NONE, GEO, GEO-ISP, RTT, Least-Connections, Connection-Limit, Bytes-Per-Second, Server-Performance ]
                            default: NONE
                          alternate:
                            type: string
                            enum: [ NONE, GEO, GEO-ISP, RTT, Least-Connections, Connection-Limit, Bytes-Per-Second, Server-Performance ]
                            default: NONE
                          preferredCPUMemoryRatio:
                            type: integer
                            minimum: 0
                            maximum: 10
                          alternateCPUMemoryRatio:
                            type: integer
                            minimum: 0
                            maximum: 10
                          checkServerStatus:
                            type: string
                            enum: [ enable, disable ]
                            default: enable
                          checkVirtualServerExist:
                            type: string
                            enum: [ enable, disable ]
                            default: enable
                          lbMethod:
                            type: string
                            enum: [ wrr ]
                            default: wrr
                          virtualServers:
                            type: array
                            items:
                              type: object
                              required:
                                - server
                                - serverMember
                              properties:
                                server:
                                  type: string
                                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                                serverMember:
                                  type: string
                                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                                ttl:
                                  type: integer
                                  minimum: -1
                                  maximum: 2147483647
                                  default: -1
                                weight:
                                  type: integer
                                  minimum: 1
                                  maximum: 255
                                  default: 1
                                backup:
                                  type: string
                                  enum: [ enable, disable ]
                                  default: disable
                        x-kubernetes-validations:
                          - rule: "(self.preferred == 'Server-Performance' ? has(self.preferredCPUMemoryRatio) : !has(self.preferredCPUMemoryRatio))"
                            message: "When preferred is 'Server-Performance', 'preferredCPUMemoryRatio' must be set. Otherwise, don't set it."
                          - rule: "(self.alternate == 'Server-Performance' ? has(self.alternateCPUMemoryRatio) : !has(self.alternateCPUMemoryRatio))"
                            message: "When alternate is 'Server-Performance', 'alternateCPUMemoryRatio' must be set. Otherwise, don't set it."
                vdom:
                  type: string
                  pattern: '^[a-zA-Z]+[-A-z0-9_.]+$'
                  x-kubernetes-validations:
                    - message: "Vdom of GLB host can not be changed."
                      rule: self == oldSelf
            status:
              type: object
              properties:
                status:
                  type: string
                  default: Pending
      subresources:
        status: {}
